---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app-deploy
  labels:
    app: nginx-web-app
    builder: jahangir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-app
      builder: jahangir
  template:
    metadata:
      labels:
        app: nginx-web-app
        builder: jahangir
    spec:
      containers:
      - name: nginx-web-app
        image: sin.ocir.io/axsfl6gebhpo/project01/mywebapp:v2
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: my-docker-sec-01
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-app-service
  labels:
    app: nginx-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 32001
    #name: nginx-web-app-port
  selector:
    app: nginx-web-app
    builder: jahangir
